[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  # Omit NEXT_PUBLIC_* keys from secrets scanning
  # These are intentionally public Supabase credentials designed for client-side use
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
